trigger:
  branches:
    include:
    - master
  tags:
    include:
    - '*'

pr:
- master

resources:
  repositories:
  - repository: azure_template
    type: github
    name: mdolab/.github
    endpoint: mdolab

extends:
  template: azure/azure_template.yaml@azure_template
  parameters:
    REPO_NAME: baseclasses
    IGNORE_STYLE: false
    PRIVATE: false
    PYPI: true